import fs from "node:fs/promises"
import path from "node:path"
import {
  FilterableNotificationProps,
  INotificationModuleService,
  MedusaContainer,
} from "@medusajs/framework/types"
import { ContainerRegistrationKeys, Modules } from "@medusajs/framework/utils"
import { packoasisConfig } from "../packoasis-config"
import { RenderedEmail } from "./templates"

export type SendEmailInput = {
  to: string | string[]
  email: RenderedEmail
  template: string
  idempotencyKey?: string
  resourceId?: string
  resourceType?: string
  headers?: Record<string, string>
}

/**
 * Sends through Medusa's Notification module (Resend / SendGrid / local
 * provider, see medusa-config.ts). Never throws: automation emails must not
 * break checkout or quoting. Returns true when every recipient got the email,
 * including recipients whose idempotency key was already delivered.
 */
export async function sendEmail(
  container: MedusaContainer,
  input: SendEmailInput
): Promise<boolean> {
  const logger = container.resolve(ContainerRegistrationKeys.LOGGER)
  const recipients = (Array.isArray(input.to) ? input.to : [input.to]).filter(
    Boolean
  )
  if (!recipients.length) {
    return false
  }

  const previewDir = process.env.PACKOASIS_EMAIL_PREVIEW_DIR
  if (previewDir) {
    try {
      await fs.mkdir(previewDir, { recursive: true })
      const file = `${Date.now()}-${input.template}-${recipients[0].replace(/[^a-z0-9@.]+/gi, "_")}.html`
      await fs.writeFile(path.join(previewDir, file), input.email.html)
    } catch (error) {
      logger.warn(`[email] preview write failed: ${(error as Error).message}`)
    }
  }

  // softDeleteNotifications is generated by MedusaService but not typed.
  const notificationService = container.resolve(
    Modules.NOTIFICATION
  ) as INotificationModuleService & {
    softDeleteNotifications(ids: string[]): Promise<unknown>
  }
  let sent = true
  for (const to of recipients) {
    const idempotencyKey = input.idempotencyKey
      ? `${input.idempotencyKey}:${to}`
      : null
    try {
      if (idempotencyKey) {
        // Medusa retries a FAILURE row under a new id it never inserts, so the
        // retry delivers and then throws. A delivered (or in-flight) key counts
        // as sent; a failed one is soft-deleted (the unique index only covers
        // live rows) so the retry is a clean insert.
        const existing = await notificationService.listNotifications(
          { idempotency_key: idempotencyKey } as FilterableNotificationProps,
          { select: ["id", "status"] }
        )
        if (existing.some((row) => row.status !== "failure")) {
          continue
        }
        if (existing.length) {
          await notificationService.softDeleteNotifications(
            existing.map((row) => row.id)
          )
        }
      }

      await notificationService.createNotifications({
        to,
        channel: "email",
        template: input.template,
        from: packoasisConfig.emailFrom() ?? null,
        content: {
          subject: input.email.subject,
          html: input.email.html,
          text: input.email.text,
        },
        data: { subject: input.email.subject },
        provider_data: {
          reply_to: packoasisConfig.replyTo(),
          headers: input.headers ?? {},
        },
        trigger_type: "packoasis",
        resource_id: input.resourceId ?? null,
        resource_type: input.resourceType ?? null,
        idempotency_key: idempotencyKey,
      })
    } catch (error) {
      sent = false
      logger.warn(
        `[email] ${input.template} to ${to} failed: ${(error as Error).message}`
      )
    }
  }

  return sent
}
